### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by adius** [andrewrk/waveform#10]
Here is the error-log:

```
npm install -g waveform
npm http GET https://registry.npmjs.org/waveform
npm http 304 https://registry.npmjs.org/waveform

> waveform@1.0.1 install /usr/local/share/npm/lib/node_modules/waveform
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.25/node-v0.10.25.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.25/node-v0.10.25.tar.gz
  CC(target) Release/obj.target/waveform/main.o
../main.c:4:10: fatal error: 'groove/groove.h' file not found
#include <groove/groove.h>
         ^
1 error generated.
make: *** [Release/obj.target/waveform/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/share/npm/lib/node_modules/waveform
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! waveform@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the waveform@1.0.1 install script.
npm ERR! This is most likely a problem with the waveform package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls waveform
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.25/bin/node" "/usr/local/bin/npm" "install" "-g" "waveform"
npm ERR! cwd /Users/adrian/Documents/hpi/designing interactive systems/FeetJ
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/adrian/Documents/hpi/designing interactive systems/FeetJ/npm-debug.log
npm ERR! not ok code 0
```

**Comment by andrewrk** [comment]
you're missing this dependency: https://github.com/andrewrk/libgroove

In the future I may replace this dependency with libav directly, but currently waveform depends on this library.

**Comment by andrewrk** [comment]
On a Mac that looks like:

```
brew install yasm lame cmake
git clone https://github.com/superjoe30/libgroove
git checkout 3.x
mkdir build && cd build
cmake .. -DDISABLE_PLAYER=true -DDISABLE_LOUDNESS=true
Check that the configure output looks OK.
make -j4 && sudo make install
```

on Ubuntu it's as easy as:

```
sudo apt-add-repository ppa:andrewrk/libgroove
sudo apt-get update
sudo apt-get install libgroove-dev
```

**Comment by adius** [comment]
I'm on mac ;-) …and it worked. Thanks!
But that's a really complicated installation. You should definitely simplify it! ^^

**Comment by andrewrk** [comment]
I agree. I plan to make a pull request to brew soon.

**Comment by adius** [comment]
:+1:

**Comment by andrewrk** [comment]
from the [brew wiki](https://github.com/Homebrew/homebrew/wiki/Acceptable-Formulae): "We will reject formulae that seem too obscure, partly because they won’t get maintained and partly because we have to draw the line somewhere. We frown on authors submitting their own work unless it is very popular."

So if you want to increase chances of brew accepting the pull request when I make it, give [libgroove](https://github.com/andrewrk/libgroove) a star :)

**Comment by adius** [comment]
haha =D  ...OK, deal. I gave it a star. =P
